from random import choice

from riobot import HELP
from rionify.core import edit, get_translation, riobot

# ================= CONSTANT =================
ECEM_STRINGS = [
    "Kamu adalah cinta masa kecilku",
    "Wajar aku tidak tahu nama-nama teman pacarku",
    "Aku sedang terburu-buru sekarang, tidak bisakah kita mundur saja nanti? Aku akan kembali lagi.",
    "Tidak, aku tidak marah",
    "Jika kamu menyadari ini, itu bukan masalah bagiku lagi",
    "Mulai sekarang, tidak ada lagi Ecem dalam hidupmu!",
    "Punya teman yang memberikan celana olahraganya saat hujan ",
    "Maukah kamu mekar sendirian? Kesepian, bunga.",
    "Saya tidak memaafkan, saya akan memanggil ibu saya. Dia akan melakukan apa yang diperlukan.",
    "Jangan main-main dengan rambutku",
    "Kamu sedang mempermainkan rambutku ketika aku menyuruhmu untuk tidak melakukannya. Tolong kejar aku.",
    "Aku tidak datang ke tubuh atau sesuatu, aku akan menunggu mati di samping",
    "Kami bukan musuh, aku hanya tidak nyaman berada di tempat dia",
    "Kejar aku, aku tidak menginginkanmu",
    "Lagu Murat Boz sama sekali tidak menghibur saya",
    "Bertobatlah, matikan, kami akan dipukul",
    "Saya ingin memiliki tiga anak perempuan",
    "Jika aku menikahinya, jadilah saksi pernikahanku",
    "Ehehehe lucu sekali, ayo pergi",
    "Maukah kamu pergi dan berbicara dengannya?",
    "Apa yang terjadi padamu? Apakah kamu ingin menceritakannya?",
    "Tolong beri tahu saya. Apakah ini sangat istimewa?",
    "Ayo, mari kita pergi ke laki-laki",
    "Apakah kamu baik-baik saja?",
    "Terima kasih ",
    "Aku akan kembali nanti, lalu kita mundur, oke?",
    "Kami membubarkan grup guys",
    "Grup kita bubar guys??? Aku panggil dia apa?",
    "Amit-amit",
    "Ayo, kamu admin, bagikan grup",
    "Selamat malam",
    "Aku mengatakan semuanya, kamu ceritakan sedikit",
    "Saya mengatakan kepadanya untuk leluconnya, saya tidak sedang diet",
    "Saya tidak tahu apakah Anda memilikinya, saya berkata, saya bertanya kepada beberapa orang lagi, apakah Anda memiliki kesempatan untuk mendapatkan cetakan?",
    "Pertanyaan dalam segitiga, situs ke-3",
    "Jika tidak, tidak perlu",
    "Tidak, aku menemukan seseorang",
    "Ya, saya sudah melakukannya, terima kasih",
    "Kuda saya, periksa untuk melihat apakah itu dia",
    "Pokoknya, kamu bisa membawa apa yang kamu bawa",
    "Siapa yang mengatakan apa padamu?",
    "Mereka mengambil kepemilikan karena mereka seperti saudara saya",
    "Tidak ada yang buruk",
    "Saya tersinggung ketika Anda melakukannya, tapi kemudian saya katakan tidak apa-apa",
    "Mereka juga tahu, mereka bereaksi darinya",
    "Jadi tidak ada masalah",
    "Sama-sama",
    "Terima kasih, maaf ponsel saya rusak, saya baru saja melihatnya 😊",
    "Ya. Apakah saya berhutang kebohongan? Ya, apakah saya berhutang kebohongan? Apakah saya berhutang kebohongan?",
    "Apa-apaan",
    "Jangan selesaikan ujian demi Tuhan",
    "Bahkan jika Anda menghapus pesan, itu muncul di notifikasi",
    "Apa yang dia katakan?",
    "Saya menulis sesuatu kepada seseorang, lalu saya menghapusnya. Dia mengatakan apa yang Anda tulis, saya tidak mengatakannya. Kemudian dia membuka apa yang saya tulis dari notifikasi dan menulisnya kepada saya.",
    "Mzkddkslsllldldldld",
    "Kami melakukannya secara kolektif, bukan, setelah hal-hal yang tidak menyenangkan terjadi.",
    "Jangan bicara",
    "Saudaraku, itu tidak bohong, itu tidak cukup",
    "Bagaimana jika aku selalu takut terjadi padaku?",
    "Andai saja aku beruntung",
    "Aku tidak bisa ikut permainan atau apapun",
    "Bertobatlah, kamu selalu mengatakan kelas yang tidak boleh",
    "Lagi pula, aku tidak berbicara denganmu",
    "Apa yang kamu perpanjang, itu berubah",
    "Diam, tidak ada yang berbicara denganmu",
    "Aku sangat merindukanmu ️",
    “Dengan hormat, syukur dan rindu”,
    "Sayangku, paman, segalanya bagiku, semoga berhasil prajuritku ️",
    "#Tanpa Filter",
    "Aku lelah dan sakit",
    "Aku bosan, bicaralah padaku. Aku berjanji tidak akan tersinggung.",
    "Dia sangat terjebak",
    "Kalau begitu, jika aku berada di urutan ke-11 dengan begitu banyak kesalahan",
    "Dengan siapa kamu berbicara, aku tidak mengerti apa-apa",
    "Kamu sakit, Lan",
    "Apa yang kamu katakan, sksödödoföfçgççşşş",
    "Aku tidak ingat pernah tertawa begitu banyak",
    "Berapa menit yang kau habiskan, bodoh",
    "Diam, kamu sudah di sana sejak pagi Ecem Ecem dmdkdmdmdmföfögö",
    "Aku tertawa seperti orang idiot di rumah, diam",
    "Bertobatlah Tuhan",
    "Jangan kejar aku jam segini",
    "Tenang Raka",
    "Mencoba memahami selama 5 jam",
    "Cukup, tidurlah",
    "Diamlah manusia",
    "Lihat apa yang dikatakan orang yang tertawa gahahaha",
    "Besok kamu tidak akan menyenangkan sama sekali",
    "Aku marah kok, jangan main-main sama aku sjdkdkkdmfgm",
    "Omong-omong, saya tidak memegang wajah saya seperti itu agar telepon tidak muncul, saya tidak tahu mengapa djjd",
    "Aku gadis yang berulang tahun ssst. Perubahan seperti apa yang kamu harapkan dkdkdk",
    "Lihat daring",
    "Hari apa pelajaran musiknya? Aku berjanji pada guru.",
    "Kalian berdua mengatakan cheddar di belakangku dan kalian mengatakan saudaraku",
    "Dia berjalan seperti ini ahahahahahahahahaha",
    "Dalam setiap momenku",
    "BFF♥️",
    "Lagi, baru, lagi ️",
    "Kami memiliki sejuta kenangan indah yang tidak dapat saya muat di sini, selalu.",
    "Selamat ulang tahun kakak, aku sangat mencintaimu ️",
    "Saya menyatakan hari terbaik ️",
    "Kita tidur bareng tapi tetep tau sjskkskkskss️",
    "Kami merindukanmu ️",
    "Ula ",
    "Lokasinya bagus",
    "Terus terhibur dengan sisa musim panas",
    "Bro, aku sudah waspada, jangan menangis, kita akan terbakar ️",
    "Aku terlalu merindukanmu sekarang",
    "Aku tidak ingin Kajsjskkskskskdksksdsjjsksks meninggalkanku️",
    "Jika itu dia, aku akan membuat dua tawa, aku sadar, aku tidak tahan️",
    "Bagaimana juga",
    "😔 menjatuhkannya setiap saat",
    "Biarkan musim panas datang sekarang kkkk",
    "SAYA MAKAN KAMU",
    "Kenapa kau membuatku kesal ",
    "Sensi 1,55",
    "Lihat seberapa baik kamu tahu",
    "jangan mengoceh sjsjkskskskskkslslskskskssklsks",
    "membuat tertawa",
    "Ya Tuhan, aku ketinggalan banyak, aku terkejut",
    "Apa maksudmu sudah 2 tahun",
    "Saya mengerti semuanya, tapi apa itu China sjdjdkmdmxmxmmxmxkc",
    "Aku akan membuangnya kemana saja",
    "Jika saya menemukan cahaya, saya pasti akan mengambil 37478383 foto",
    "Apakah aku memberitahumu bahwa aku naksir??",
    "Apakah kamu bodoh sjdjdkdkkdkdkdkdkd",
    "Apa yang dilakukan kehidupan yang membuat saya bertambah banyak berat badan terhadap Anda - '2018",
    "Ingat cepat",
    "Ayyyyyy ️",
    "Askksksllslsldkd dengan kepala apa kita menggambar ini",
    "Kalau tidak saya potong nanti kita tersinggung sjskkdkdksksmdk",
    "Bagaimana itu bisa sampai di sini dari berat badan saya",
    "Bro, kamu belum melihatku selama setahun, kamu tahu",
    "Lepaskan kami sekarang",
    "Garpu",
    "Saya mulai diet, topik ditutup",
    "Lihat, kenapa tidak",
    "Cerita utama telah ditinggalkan",
    "Siapa tahu, saat-saat aku bahagia - baru 2018 -",
    "Aku tidak berkomentar lagi",
    "Gelombang Az tidak mengubah cermin itu ",
    "Selamat tinggal",
    "Aku terlalu rindu kepadamu",
    "Jangan tinggal di cerita",
    "Ilmu apa yang tidak memotret dimanapun ia menemukannya",
    "Bagaimana cuaca di sana",
    "Saya sangat beruntung untuk memiliki mu",
    "Bisakah kita kembali ke hari-hari ini secepat mungkin",
    "Ini milikku sekarang",
    "Aku merindukanmu dan rambut panjangku ",
    "Akhirnya kita dipertemukan kembali ️",
    "Aku bahkan merindukanmu ",
    "Tuhan aku sangat bahagia lagi",
    "Aku bahagia 1 tahun yang lalu",
    "Yaaaaaa 😔 ♥️",
    "AKU ADALAH SEGALANYA ❤️💜🧡🖤💗💙💖💕💝💛💘♥💓",
    "Lanjut dari serialnya, jangan tinggal di cerita",
    "Kak, kenapa aku terlihat berbeda di setiap foto",
    "Sayang kecilku ️",
    "Lingkaran hitam saya dan saya tidak pantas menerima ini",
    "Sjskdksksjdksl tidak ada sedetik pun aku tidak gugup",
    "Tidak ada hari dimana mataku tidak lelah",
    "Biarkan musim panas kembali dan kita minum setiap hari",
    "Suatu hari kita memperebutkan anjing yang keras kepala djjdjdjd",
    "Ini skskkdkdkdlskskd untukmu",
    "Apa yang dikatakan pemenang dalam perjudian",
    "SJSKKDKSSKSKSKKS TEMAN PALING GILA DI DUNIA Aku senang memiliki kalian ️♥️♥️♥️",
    "Sayangku tidak pernah bisa berdiri normal ️♥️♥️♥️",
    "Ibunya Lambuuuu",
    "Tidak benar-benar Barbie",
    "Aku merindukan saat-saat ini",
    "Kelas 9, sayang Izmir ️",
    "377383843. Coba saja, saya kira cukup neyss untuk hari ini",
    "Aku sangat merindukanmu",
    "Memenuhi Syarat untuk Menjadi Postingan",
    "Ulang tahun sayang ️♥️",
    "Saya belum pernah melihat tweet yang lebih benar",
    "Aku bahkan tidak percaya aku mengatakan ini tapi aku sangat merindukannya ️♥️♥️",
    "Sepertinya aku merindukan rambut lamaku",
    "Bahkan jika itu 10 tahun, pertahankan lelucon yang sama",
    "Kami Mulai Lagi",
    "Sjskkskskdkkdkdkdk ke media sosial",
    "Kadang aku juga",
    "Cukup sudah",
    "Sjskjdkdkskskskkskks",
    "Aku juga bertanya-tanya di mana kamu berada",
    "Carilah hari ini",
    "GN",
    "gn",
    "Makhluk termanis di dunia",
    "Ya hahahahahahahahaha dia satu-satunya cintaku",
    "Ayo pergi ke Izmir",
    "Ini dia Bu Seden",
    "Saya tidak menyadari djskkskskskkssksk di belakang",
    "Keindahan sekolah",
    "Potong pesan saya dulu",
    "Akhirnya kita dipertemukan kembali",
    "Karena sepupumu ",
    "Ssst",
    "Kamu suka melebih-lebihkan",
    "Poros",
    "AYO BERDAMAI SEKARANG",
    "Cintaku ",
    "Sisa Malam",
    "Oooo Bung, beraninya kau membicarakannya",
    "Sayangku♥",
    "Malu yang punya djdkdkkd",
    "Aku sayang ",
    "Selamat malamtttt",
    "Ringkasan kehidupan cintaku",
    "Inilah yang terjadi ketika Anda kebal",
    "Cintaku ",
    "Selamat malam",
    "Pengalaman berbicara",
    "Aku juga ",
    "Cintai bungaku♥♥♥",
    "Ini skskkdkdkdlskskd untukmu",
    "Ksnkskzksls ",
    "Sakit dan lelah",
    "Ksjskskskskssks",
    "Sayangku♥♥♥♥",
    "Msmsks",
    "Bukankah kita punya konser lagi, tapi",
    "Cintaku cintaku♥♥",
    "Dito",
    "Pergi djdkdmfmgöögmdmdmdmd",
    "Sialan oke, kamu menyesal sjskdkkskskslsmskldmdlddk",
    "Serial maaf sjkdkdkdksls",
    "Kami memenangkan pertandingan dan Anda sudah sering melihatnya",
    "Terima kasih padaku",
    "Anda meminta saya untuk memainkan semua pertandingan dan kemudian Anda melakukannya di privasi saya",
    "Kskskskskskskskssks",
    "SHJSJSKDKDKSKDK",
    "Tidur yang cukup, kamu ada pelajaran di pagi hari",
    "kdkdkdkdkdkdmdmdmdm aku muak batuk di kelas, ini terlalu banyak sjskkfksks",
    "OKE",
    "Sjkdkdkdkdlskdkxkdkdkdld air terjun mengatakan terakhir kali Anda ingin burung, tapi Anda masih tahu",
    "SJDKFKLGLDKDKDLSLDKDKDKDLDLDLLD",
    "Igg massal",
    "Saya akan mengingat",
    "Jangan patahkan kepalaku lain kali tapi",
    "NSSNMDMDMSMSMDM",
    "Nsnsmsmdmdmdmskkdms",
    "Bagus kiiii",
    "Karena suaramu, aku membuang suara itu, kamu berteriak, teman seperti teman kskskskskkdmsksmsmsmmdmddk",
    "Jika kita segera bersama, kita akan menulis ujian ini skskdkdkksksks",
    "Bayangkan besok guru mengganti angka",
    "Aku akan tetap sjjdjfjdkskskdkdkdkkdksks",
    "Ini bukan tentang belajar bersama, saudara, itu adalah lingkungan yang kita habiskan bersama",
    "Skkskkkss aku hanya punya ini ",
    "Bahkan jika tali memiliki lidah, ia berbicara",
    "Saya memiliki seri sjsjskdmmsksks",
    "Abarttttt",
    "Sudut Babush bagus tapi kami juga pernah lemah",
    "Tentu saja pelatih",
    "Wah itu 2 tahun yang lalu",
    "Aslan, kami berdamai setelah 2 bulan atas dia",
    "Djdjdkkdkdkdkd karena dia Seden",
    "Jangan ganggu",
    "Yayaya",
    "Ulang tahun sayang♥♥ -foto mendesak @sedenogen",
    "Sjsjdjjsksksksks bukan yang aku rindukan, tapi yang SANGAT aku rindukan",
    "Yaaaa",
    "Jangan bilang, aku akan melukis",
    "Kamu pasti anak masa depanku",
    "Ayyyyyy",
    "Saya perhatikan bahwa saya pingsan di foto ini",
    "Suasana hati saat ini: HARI LIBUR!",
    "Aku hampir meledak karena bosan",
    "Kami bukan bihter ziyagil, tapi kami juga sangat menderita sjjsjsjskd",
    "Lanjutkan sampai Anda bosan dengan efeknya",
    "Dia berkata biarkan pertunjukan dimulai",
    "Piyamaku dan kamu♥",
    "Apakah untuk memasuki tahun baru sendirian di rumah 0/10",
    "Serial lelah",
    "10/10",
    "Hitam adalah warna favoritku",
    "Alhamdulillah hari ini kami mati kelelahan juga",
    "Pasangan terbaik",
    "Igg",
    "Pasti Lelah",
    "Selamat malam",
    "Potongan rambut adalah penyesalan yang jelas",
    "Skor saya untuk hari ini adalah 0",
    "Bibi ",
    "Cintaku♥♥♥",
    "Kamu yang paling cantikllll♥♥♥",
    "Aku sayang♥",
    "Lempar sesuatu yang bagus untuk sekali",
    "Sayang♥",
    "Cintaku♥",
    "Aku juga mencintaimu sayang ",
    "Kurasa emoji itu salah ",
    "Terima kasih ",
    "Sayangku♥",
    "Banyak ",
    "Yang paling spesial♥",
    "Bola",
    "Aku mencintaimuiii",
    "DM untuk perawatan psikologis",
    "Tarik itu seperti kamu sedang menyelesaikannya",
    "Kamu menghitung menit untuk berhenti berbohong",
    "Aku kangen nyanyi di belakang sama kamu dan makan jajan",
    "Saya membuka mata saya dengan lagu galatasaray sjsjdkdkdkkdkd",
    "Bagus, lewat sini sjskkfskdkfdkkdkddk",
    "Gn priv keluargaku♥️♥️♥️",
    "Aku tidak tidur sjskkskdkdkd",
    "Mataku hitam, aku mati",
    "Tidak ada yang akan mengerti tautan ini sjskksksksksk",
    "Jangan lakukan itu, kita akan terbakar",
    "skamaksksksksksks",
    "Saya harap kita bisa melihatnya sekarang",
    "juga bagaimana",
    "Lokasi kita jelas",
    "Saya beruntung tidak semua orang dapat menemukan saudara perempuan seperti ini ️♥️♥️♥️",
    "Apakah kamu orang tersayangku????",
    "😳♥️♥️",
    "Maaf, ada apa",
    "Kamu seperti bayi kkk sayangku",
    "Ssst diam atau aku akan percaya padamu",
    "Selamat malam sayangku️♥♥♥",
    "Sedih yang mencintaimu, patuhi perintah",
    "Aku tidak mengenali",
    "Kelas mana",
    "Tidak ada seorang pun dari sekolah yang mengikutimu?",
    "Ada 12 orang yang saya ikuti",
    "Tapi tidak satupun dari mereka mengikutimu",
    "Kavuştukkkk",
    "dengan bayiku💘",
    "Tidak ada resep untuk kerinduan ini ",
    "Suasana hati.",
    "Ilmu apa yang tidak jatuh ke dalam tawa pada akhirnya",
    "Apakah setiap orang harus begitu egois?",
    "❔",
    "Tunggu, katanya ",
    "Biarkan ini tinggal di sini juga",
    "ANDA ",
    "Sssttt",
    "💗💗",
    "Oh Seden saya ... cewek kecil saya",
    "💓💓💓💓",
    "Aku memuaskan kerinduanmu dengan bajumu.",
    "Hush, kau terlihat sangat berbeda",
    "Aku menceritakan masalahku pada Seden. Seden:",
    "Sialan jiwaku ",
    "😘😘",
    "Gangguan saraf mendadak",
    "Kami sedang menguji apakah kami sedang online #whatsapp Anda membakar kami",
    "Djjdkdkmdoödööd",
    "Aku tidak mengambilnya, Seden yang mengambilnya",
    "Pak, silahkan datang ke pelajaran kami selanjutnya",
    "Mari kita berbagi beberapa teman yang tidak jujur ​​️♥️♥️♥️",
    "kamu hanya menulis di hari ulang tahunku",
    "Kalau bohong sebut saja bohong djjdjdkdkksks",
    "👅♥️♥️♥️",
    "Apakah masih belum ada SJSJJDJDKSKSKSKKKSKSKDK",
    "Seluruh sekolah mengerti @CiyanogenOneTeams tidak mengerti bahwa saya tidak akan baik padanya Jsjsjdkskskskskskl",
    "KSKDKDKDKDKSKKKSKDKDKKD",
    "LAN REMINDER sjjdjdjdkdkdkdkdk ayo foto APA SJSKSKSKSK",
    "Aku bersumpah aku belum melihat lebih banyak penggemar jdjdkdkdkd",
]
# ================= CONSTANT =================
'''Copyright (c) @Sedenogen | 2020'''


@riobot(pattern='^.ecem$')
def ecemify(message):
    ecem(message)


def ecem(message):
    # Ecem'in sözlüğü
    edit(message, choice(ECEM_STRINGS))


HELP.update({'ecem': get_translation('ecemInfo')})
